/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TransformationsRouteImport } from './routes/transformations'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNutritionRouteImport } from './routes/app.nutrition'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppWorkoutRouteImport } from './routes/app.workout'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardCheckinsRouteImport } from './routes/dashboard.checkins'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardNutritionRouteImport } from './routes/dashboard.nutrition'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardWorkoutsRouteImport } from './routes/dashboard.workouts'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard.clients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationsRoute = TransformationsRouteImport.update({
  id: '/transformations',
  path: '/transformations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCheckinsRoute = DashboardCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNutritionRoute = DashboardNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkoutsRoute = DashboardWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/apply': typeof ApplyRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/transformations': typeof TransformationsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/workout': typeof AppWorkoutRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/checkins': typeof DashboardCheckinsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/nutrition': typeof DashboardNutritionRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/transformations': typeof TransformationsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/workout': typeof AppWorkoutRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/checkins': typeof DashboardCheckinsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/nutrition': typeof DashboardNutritionRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/app': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/apply': typeof ApplyRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/transformations': typeof TransformationsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/workout': typeof AppWorkoutRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/checkins': typeof DashboardCheckinsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/nutrition': typeof DashboardNutritionRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/apply'
    | '/coaching'
    | '/contact'
    | '/dashboard'
    | '/resources'
    | '/transformations'
    | '/app/checkin'
    | '/app/messages'
    | '/app/nutrition'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/app/workout'
    | '/dashboard/ai'
    | '/dashboard/calendar'
    | '/dashboard/checkins'
    | '/dashboard/content'
    | '/dashboard/leads'
    | '/dashboard/messages'
    | '/dashboard/nutrition'
    | '/dashboard/payments'
    | '/dashboard/progress'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/workouts'
    | '/app/'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/dashboard/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/coaching'
    | '/contact'
    | '/resources'
    | '/transformations'
    | '/app/checkin'
    | '/app/messages'
    | '/app/nutrition'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/app/workout'
    | '/dashboard/ai'
    | '/dashboard/calendar'
    | '/dashboard/checkins'
    | '/dashboard/content'
    | '/dashboard/leads'
    | '/dashboard/messages'
    | '/dashboard/nutrition'
    | '/dashboard/payments'
    | '/dashboard/progress'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/workouts'
    | '/app'
    | '/dashboard'
    | '/dashboard/clients/$id'
    | '/dashboard/clients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/apply'
    | '/coaching'
    | '/contact'
    | '/dashboard'
    | '/resources'
    | '/transformations'
    | '/app/checkin'
    | '/app/messages'
    | '/app/nutrition'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/app/workout'
    | '/dashboard/ai'
    | '/dashboard/calendar'
    | '/dashboard/checkins'
    | '/dashboard/content'
    | '/dashboard/leads'
    | '/dashboard/messages'
    | '/dashboard/nutrition'
    | '/dashboard/payments'
    | '/dashboard/progress'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/workouts'
    | '/app/'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/dashboard/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  CoachingRoute: typeof CoachingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  TransformationsRoute: typeof TransformationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformations': {
      id: '/transformations'
      path: '/transformations'
      fullPath: '/transformations'
      preLoaderRoute: typeof TransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workout': {
      id: '/app/workout'
      path: '/workout'
      fullPath: '/app/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/checkins': {
      id: '/dashboard/checkins'
      path: '/checkins'
      fullPath: '/dashboard/checkins'
      preLoaderRoute: typeof DashboardCheckinsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nutrition': {
      id: '/dashboard/nutrition'
      path: '/nutrition'
      fullPath: '/dashboard/nutrition'
      preLoaderRoute: typeof DashboardNutritionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workouts': {
      id: '/dashboard/workouts'
      path: '/workouts'
      fullPath: '/dashboard/workouts'
      preLoaderRoute: typeof DashboardWorkoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/clients/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCheckinsRoute: typeof DashboardCheckinsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNutritionRoute: typeof DashboardNutritionRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWorkoutsRoute: typeof DashboardWorkoutsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCheckinsRoute: DashboardCheckinsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNutritionRoute: DashboardNutritionRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWorkoutsRoute: DashboardWorkoutsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsIdRoute: DashboardClientsIdRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ApplyRoute: ApplyRoute,
  CoachingRoute: CoachingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  TransformationsRoute: TransformationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
